# Generated by Django 5.0.14 on 2026-06-19 20:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('tipo_estrutura', models.CharField(choices=[('ZINCO', 'Zinco / Metálica'), ('FIBROCIMENTO', 'Fibrocimento'), ('SOLO', 'Solo'), ('CERAMICA', 'Cerâmica'), ('LAJE', 'Laje')], max_length=20)),
                ('fase_atual', models.CharField(choices=[('LEAD', 'Lead'), ('PROPOSTA', 'Proposta Apresentada'), ('CONTRATO', 'Contrato Assinado'), ('CONCLUIDO', 'Projeto Concluído')], default='LEAD', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Conta de Energia, Foto do Padrão, Documentos', max_length=100)),
                ('arquivo', models.FileField(upload_to='clientes/anexos/')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='crm.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Dimensionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_mensal_kwh', models.FloatField(help_text='Consumo médio mensal em kWh')),
                ('irradiacao_local', models.FloatField(help_text='Irradiação solar local (kWh/m²/dia) - Ex: 5.2')),
                ('potencia_painel_wp', models.IntegerField(default=550, help_text='Potência da placa selecionada em Watts (Ex: 550)')),
                ('potencia_sistema_kwp', models.FloatField()),
                ('qtd_placas', models.IntegerField()),
                ('area_necessaria_m2', models.FloatField()),
                ('peso_total_kg', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensionamento', to='crm.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total_investimento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prazo_entrega_dias', models.IntegerField(default=60, help_text='Prazo para homologação e instalação')),
                ('validade_proposta_dias', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('GERADA', 'Gerada'), ('ENVIADA', 'Enviada ao Cliente'), ('ACEITA', 'Aceita (Aguardando Contrato)'), ('RECUSADA', 'Recusada')], default='GERADA', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='crm.cliente')),
                ('dimensionamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.dimensionamento')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(help_text='Ex: CTR-2026-001', max_length=50, unique=True)),
                ('data_assinatura', models.DateField(default=django.utils.timezone.now)),
                ('token_assinatura_digital', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo_contrato_pdf', models.FileField(blank=True, null=True, upload_to='contratos/assinados/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('proposta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='crm.proposta')),
            ],
        ),
    ]
