# Generated by Django 5.0.14 on 2026-06-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposta',
            old_name='criado_em',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='dimensionamento',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='prazo_entrega_dias',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='status',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='validade_proposta_dias',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='valor_total_investimento',
        ),
        migrations.AddField(
            model_name='proposta',
            name='consumo_kwh',
            field=models.FloatField(default=0, verbose_name='Consumo Médio Mensal (kWh)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposta',
            name='hsp',
            field=models.FloatField(default=4.5, verbose_name='Horas de Sol Pleno (HSP Local)'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='potencia_painel',
            field=models.IntegerField(default=550, verbose_name='Potência do Painel (W)'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='potencia_usina',
            field=models.FloatField(blank=True, null=True, verbose_name='Potência da Usina (kWp)'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='qtd_modulos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Módulos'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='valor_investimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total (R$)'),
        ),
    ]
