# Generated by Django 5.0.14 on 2026-06-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_criado_em_proposta_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_active',
        ),
        migrations.AddField(
            model_name='cliente',
            name='consumo_kwh',
            field=models.PositiveIntegerField(default=0, help_text='Consumo atual do cliente (ex: 1000 kWh)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='marca_inversor',
            field=models.CharField(blank=True, help_text='Marca do inversor que será usado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='potencia_painel',
            field=models.PositiveIntegerField(default=550, help_text='Potência dos painéis/placas em Watts (ex: 550)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='potencia_usina',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculado: Potência total da usina em kWp', max_digits=6),
        ),
        migrations.AddField(
            model_name='cliente',
            name='producao_estimada_kwh',
            field=models.PositiveIntegerField(default=0, help_text='Produção estimada que o cliente quer para a usina (ex: 1500 kWh)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='qtd_modulos',
            field=models.PositiveIntegerField(default=0, help_text='Calculado: Quantidade de placas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_investimento',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculado: Preço final do projeto', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_estrutura',
            field=models.CharField(choices=[('ZINCO', 'Zinco / Metálica'), ('FIBROCIMENTO', 'Fibrocimento'), ('SOLO', 'Solo'), ('CERAMICA', 'Cerâmica'), ('LAJE', 'Laje')], default='CERAMICA', max_length=50),
        ),
    ]
