# Generated by Django 5.0.14 on 2026-06-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_cliente_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fase_atual',
            field=models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('PROPOSTA', 'Proposta Apresentada'), ('CONTRATO', 'Contrato Assinado'), ('CONCLUIDO', 'Projeto Concluído')], default='ORCAMENTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_estrutura',
            field=models.CharField(choices=[('COLONIAL', 'Telhado Colonial'), ('METALICO', 'Telhado Metálico'), ('LAJE', 'Laje'), ('SOLO', 'Solo'), ('FIBROCIMENTO', 'Telhado Fibrocimento(Telhão)')], default='COLONIAL', max_length=50),
        ),
    ]
