# Generated by Django 5.0.14 on 2026-06-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_cliente_fase_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Define se o cliente está ativo no sistema (Soft Delete)'),
        ),
    ]
